version: "3.7"

services:
  php:
    image: php:7.3.6-alpine3.9
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - ${PORT}:${PORT}
    command:
        php /var/www/run.php
